on:
  push:
    branches-ignore:
      - "main"

name: validate-compatibility
jobs:
  compat:
    name: "Validate compatibility with main branch"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install
        run: make install
      - name: buf build and lint
        run: make buf-lint
      - name: build and compile test
        run: make test
      - name: run the check script
        run: ./scripts/check-proto-compabitility.sh
