on:
  push:
    branches-ignore:
      - "main"

env:
  BASE_BRANCH: protocol-squad # TODO: change to main for merging into main

name: validate-compatibility
jobs:
  compat:
    name: "Validate compatibility with main branch"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: make install
      - name: buf breaking
        run: make buf-breaking
      - name: buf lint
        run: make buf-lint
      - name: build and compile test
        run: make test
      - name: run the check script
        run: ./scripts/check-proto-compabitility.sh ${{ env.BASE_BRANCH }}
